export const W = 960;
export const H = 640;
export const TANK_SIZE = 16;
export const BULLET_SPEED = 6;
export const BULLET_LIFE = 30;       // ~1.5s at 20 TPS
export const SHOOT_CD = 10;          // ~0.5s at 20 TPS
export const FLAG_SIZE = 14;
export const FLAG_HP = 200;
export const TANK_HP = 60;
export const TANK_SPEED = 1.8;
export const AI_SPEED = 1.4;
export const WALL_COUNT = 45;
export const RESPAWN_TIME = 60;      // 3s at 20 TPS
export const PICKUP_SPAWN_INTERVAL = 10; // ~0.5s at 20 TPS
export const SPEED_BUFF_DUR = 160;   // 8s at 20 TPS
export const FIRE_BUFF_DUR = 160;    // 8s at 20 TPS
export const SPEED_MULT = 1.7;
export const FIRE_CD_MULT = 0.35;
export const HEAL_AMOUNT = 35;
export const MAX_PICKUPS = 6;
